name: BattleRoyale
version: '1.0-SNAPSHOT'
main: xyz.leafing.battleRoyale.BattleRoyale
api-version: '1.21'
depend: [Vault,MiniGameManager]

commands:
  br:
    description: Main command for the Battle Royale plugin.
    usage: |
      /br create <amount> - Starts a new game with an entry fee.
      /br join - Joins the current game.
      /br leave - Leaves the game lobby.
